# Generated by Django 6.1 on 2026-08-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="cat_images",
            new_name="images",
        ),
    ]
