# Generated by Django 6.1 on 2026-09-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "Cartitem", "verbose_name_plural": "Cartitems"},
        ),
    ]
