# Generated by Django 6.1 on 2026-08-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="data_joined",
            new_name="date_joined",
        ),
    ]
