# Generated by Django 6.1 on 2026-08-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catogery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catogery_name", models.CharField(max_length=50)),
                ("slag", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, max_length=255)),
                (
                    "cat_image",
                    models.ImageField(blank=True, upload_to="photoes/categories/"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
