# Generated by Django 6.1 on 2026-08-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catogery",
            name="slag",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
