# Generated by Django 6.1 on 2026-08-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_catogery_slag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catogery",
            name="cat_image",
            field=models.ImageField(blank=True, upload_to="photos/categories/"),
        ),
    ]
