# Generated by Django 6.1 on 2026-08-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_catogery_cat_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catogery",
            old_name="slag",
            new_name="slug",
        ),
    ]
